[package]
name = "unicode_bot"
version = "0.2.0"
authors = ["Juan Potato <hasantiny@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.9", features = ["trust-dns"] }
tokio = "0.1"
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }
charname = "0.1.2"
tg_botapi = "0.6.0-alpha.0"
