[package]
name = "unicode_bot"
version = "0.2.0"
authors = ["Juan Potato <hasantiny@gmail.com>"]

[dependencies]
charname = "0.1.0"
telegram-bot = "0.6"
failure = "0.1"
tokio-core = "0.1"
futures = "0.1"

